language: php
php:
  - 5.5

before_script:
   - composer install --prefer-source --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
